export const ToastCause = {
  // Transaction related
  TRANSACTION_SUBMITTED: 'TRANSACTION_SUBMITTED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  TRANSACTION_ERROR: 'TRANSACTION_ERROR',

  // Wallet related
  WALLET_NOT_CONNECTED: 'WALLET_NOT_CONNECTED',

  // Domain related
  DOMAIN_REQUIRED: 'DOMAIN_REQUIRED',
  DOMAIN_CHECK_SLOW: 'DOMAIN_CHECK_SLOW',
  DOMAIN_CHECK_FAILED: 'DOMAIN_CHECK_FAILED',

  // Profile related
  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PROFILE_CREATE_FAILED: 'PROFILE_CREATE_FAILED',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PROFILE_SUBMIT_FAILED: 'PROFILE_SUBMIT_FAILED',

  // Image upload related
  IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
  IMAGE_UPLOAD_FAILED: 'IMAGE_UPLOAD_FAILED',
  IMAGE_INVALID_TYPE: 'IMAGE_INVALID_TYPE',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
} as const;

export type ToastCause = typeof ToastCause[keyof typeof ToastCause];
