export const ToastCause = {
  // Transaction related
  TRANSACTION_SUBMITTED: 'TRANSACTION_SUBMITTED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  TRANSACTION_ERROR: 'TRANSACTION_ERROR',

  // Wallet related
  WALLET_NOT_CONNECTED: 'WALLET_NOT_CONNECTED',

  // Domain related
  DOMAIN_REQUIRED: 'DOMAIN_REQUIRED',
  DOMAIN_CHECK_SLOW: 'DOMAIN_CHECK_SLOW',

  // Profile related
  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PROFILE_CREATE_FAILED: 'PROFILE_CREATE_FAILED',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PROFILE_SUBMIT_FAILED: 'PROFILE_SUBMIT_FAILED',
} as const;

export type ToastCause = typeof ToastCause[keyof typeof ToastCause];
