/**
 * The compiled `register` NoteScript the registry will actually accept.
 *
 * WHY THIS EXISTS — do not replace with a source recompile:
 * The network account only auto-consumes notes whose note-script MAST root is in
 * the registry's `NetworkAccountNoteAllowlist`. That allowlist is built from the
 * compiled packages in midenname-contracts-rs. Assembling equivalent source in
 * the browser SDK produces a DIFFERENT root (the frontend bundles different
 * std-lib/assembler builds than the Rust toolchain), so the note is silently
 * ignored and stays COMMITTED forever.
 * Confirmed 2026-07-02 against the assembly registry: frontend `register` root
 * 0x3ae77f… ≠ deployed 0xc12187a6….
 *
 * The bytes now come from the Rust registry rather than the assembly one, and are
 * regenerated by the contracts repo:
 *   cargo run -p integration --release --bin export-frontend -- --registry 0x...
 * which writes src/shared/generated/registry.ts. Re-run it after every redeploy.
 *
 * The Rust note is much larger than the assembly one (~34 KB vs 951 bytes) because
 * the compiled package embeds the registry interface it links against.
 */
export { REGISTER_NOTE_SCRIPT_COMPILED_B64 } from '../generated/registry';
